# Generated by Django 4.0.1 on 2022-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Approved'),
        ),
    ]
